version: "3.8"

services:
  spring-boot-app:
    image: maven:3.8.7-eclipse-temurin-17
    container_name: spring-boot-app
    working_dir: /app
    volumes:
      - .:/app  # Mount the current directory to the container's working directory
      - ~/.m2:/root/.m2  # Cache Maven dependencies for faster builds
    ports:
      - "8080:8080"  # Map port 8080 on the host to port 8080 in the container
    command: mvn spring-boot:run
